pipeline:
  test:
    image: majexa/ngn
    commands:
#      - cat insecure_key
      - chmod 600 insecure_key
      - ssh -i insecure_key -o StrictHostKeyChecking=no root@localhost dir /etc/service

services:
  dosakai:
    image: majexa/dosakai
    environment:
      EMAIL_SENDER: ci@majexa.ru
      EMAIL_SCREENSHOTS_TO: andrey.yartsev.g@gmail.com
      SMTP_EMAIL: ivan.lebedev321@gmail.com
      SMTP_PASSWORD: q3gf8wqegfv97
