pipeline:
  test:
    image: majexa/dosakai-client
    commands:
      - cd /usr/src/dosakai; bash run.sh /drone/src/test.feature

services:
  dosakai:
    image: majexa/dosakai
    environment:
      EMAIL_SENDER: ci@majexa.ru
      EMAIL_SCREENSHOTS_TO: andrey.yartsev.g@gmail.com
      SMTP_EMAIL: ivan.lebedev321@gmail.com
      SMTP_PASSWORD: q3gf8wqegfv97
